spring.application.name=mini-rippling
# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/mini_rippling
spring.datasource.username=postgres
spring.datasource.password=admin

# Hibernate settings
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# App port
server.port=8080
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
logging.level.org.springframework.transaction=DEBUG
logging.level.org.hibernate.SQL=DEBUG
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.modules=com.fasterxml.jackson.datatype.jsr310.JavaTimeModule
spring.main.allow-bean-definition-overriding=true
